# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:


# Permalinks
permalink:        pretty


# Setup
title:            Michale Gebrekiros
tagline:          'Engineering Hydrologist'
description:      'Engineering Hydrologist'
#url:              http://hyde.getpoole.com
url:              http://Mgebrekiros.github.io
baseurl:          /

author:
  name:           'Michale Gebrekiros'
#  url:            https://twitter.com/mdo

paginate:         1

# Custom vars
version:          2.1.0

github:
#  repo:           https://github.com/poole/hyde
  me: https://github.com/Mgebrekiros
